# site settings
title: Celeste's cleaning
subtitle: Business and residential professional services
email: info@celestecleaning.com
description: "cleaning services in San Diego, CA"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: "info@celestecleaning.com"
street_address:
city: San Diego
state: CA
zip_code: 
country: United States
phone: (619) 867-3203

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
    - jekyll-seo-tag
